export const SIGN_OUT = 'SIGN_OUT';
export const AUTH_NAVBAR = 'AUTH_NAVBAR';
export const GOOGLE = 'GOOGLE';
export const BOOKS_PROCESSING_STATUS = {
    PROCESSING:'PROCESSING',
    PROCESSED:'PROCESSED',
    FAILED:'FAILED'
}